### Exercise 11:

###### The `df` DataFrame is given below:

|    | weight | weight_cut |
|---:|-------:|:----------:|
| 0 | 75.0 | light |
| 1 | 78.5 | normal |
| 2 | 85.0 | heavy |
| 3 | 91.0 | heavy |
| 4 | 84.5 | heavy |
| 5 | 83.0 | heavy |
| 6 | 68.0 | light |

###### Using the `pd.get_dummies()` function convert the categorical column `weight_cut` into dummy variables.

###### In response, print the result to the console.

In [1]:
import pandas as pd

df = pd.DataFrame(data={'weight': [75., 78.5, 85., 91., 84.5, 83., 68.]})
df['weight_cut'] = pd.cut(df['weight'], bins=(60, 75, 80, 95), labels=['light', 'normal', 'heavy'])

df = pd.get_dummies(df, dtype=int)
print(df)

   weight  weight_cut_light  weight_cut_normal  weight_cut_heavy
0    75.0                 1                  0                 0
1    78.5                 0                  1                 0
2    85.0                 0                  0                 1
3    91.0                 0                  0                 1
4    84.5                 0                  0                 1
5    83.0                 0                  0                 1
6    68.0                 1                  0                 0

### Exercise 12

###### The `df` DataFrame is given below:

|    | currency |
|---:|:---------------------------|
| 0 | [PLN, USD] |
| 1 | [EUR, USD, PLN, CAD] |
| 2 | [GBP] |
| 3 | [JPY, CZK, HUF] |
| 4 | [] |

###### Assign a new column `'number'` that takes the number of items in the `currency` column.

###### In response, print the `df` DataFrame to the console.

In [2]:
import pandas as pd

data_dict = {
    'currency': [['PLN', 'USD'], ['EUR', 'USD', 'PLN', 'CAD'], ['GBP'], ['JPY', 'CZK', 'HUF'], []]
}
df = pd.DataFrame(data=data_dict)
df['number'] = df['currency'].apply(len)
print(df)

               currency  number
0            [PLN, USD]       2
1  [EUR, USD, PLN, CAD]       4
2                 [GBP]       1
3       [JPY, CZK, HUF]       3
4                    []       0

### Exercise 13

###### The `df` DataFrame is given below:

|    | currency |
|---:|:---------------------------|
| 0 | [PLN, USD] |
| 1 | [EUR, USD, PLN, CAD] |
| 2 | [GBP] |
| 3 | [JPY, CZK, HUF] |
| 4 | [] |

###### Assign a new column `'PLN_flag'` which stores `1` when the currency `'PLN'` is in the `currency` column, otherwise `0` as shown below.

###### In response, print the `df` DataFrame to the console.

In [3]:
import pandas as pd

data_dict = {
    'currency': [['PLN', 'USD'], ['EUR', 'USD', 'PLN', 'CAD'], ['GBP'], ['JPY', 'CZK', 'HUF'], []]
}

df = pd.DataFrame(data = data_dict)

df['PLN_flag'] = df['currency'].apply(lambda i:1 if 'PLN' in i else 0)
print(df)

               currency  PLN_flag
0            [PLN, USD]         1
1  [EUR, USD, PLN, CAD]         1
2                 [GBP]         0
3       [JPY, CZK, HUF]         0
4                    []         0

### Exercise 14:

###### The `df` DataFrame is given below:

|    | hashtags |
|---:|:----------------------|
| 0 | #good#vibes |
| 1 | #hot#summer#holiday |
| 2 | #street#food |
| 3 | #workout |

###### Split `hashtags` by the `'#'` sign using `pd.Series.str.split()` with argument `expand=True`.

###### You will get four columns. For example, for the second row:

```python
'#hot#summer#holiday'
```

###### it returns the following list:

```python
['', 'hot', 'summer', 'holiday']
```

###### Remove the first column from the result (the first column contains only empty strings `''`).

###### Then assign the names of the remaining columns as follows:

- `'hashtag1'`
- `'hashtag2'`
- `'hashtag3'`

###### In response, print the result to the console.

In [4]:
import pandas as pd

data_dict = {
    'hashtags': [
        '#good#vibes', 
        '#hot#summer#holiday', 
        '#street#food', 
        '#workout'
    ]
}
df = pd.DataFrame(data=data_dict)

df = df['hashtags'].str.split('#', expand = True)
df = df.drop(columns=[0])

df.columns = ['hashtag1', 'hashtag2', 'hashtag3']
print(df)

  hashtag1 hashtag2 hashtag3
0     good    vibes      NaN
1      hot   summer  holiday
2   street     food      NaN
3  workout      NaN      NaN

### Exercise 15:

###### The `df` DataFrame is given below:

|    | hashtag1 | hashtag2 | hashtag3 |
|---:|:---------|:---------|:---------|
| 0 | good | vibes | None |
| 1 | hot | summer | holiday |
| 2 | street | food | None |
| 3 | workout | None | None |

###### Create a new column `'missing'` and assign the number of missing hashtags for each row as shown below.

###### For example:

###### - row one → `1`
###### - row two → `0`
###### - row three → `1`

###### As an answer, print the `df` DataFrame to the console.

In [5]:
import pandas as pd


data_dict = {
    'hashtags': [
        '#good#vibes', 
        '#hot#summer#holiday', 
        '#street#food', 
        '#workout'
    ]
}
df = pd.DataFrame(data=data_dict)
df = df['hashtags'].str.split('#', expand=True)
df = df.drop(columns=[0])
df.columns = ['hashtag1', 'hashtag2', 'hashtag3']

In [6]:
df

  hashtag1 hashtag2 hashtag3
0     good    vibes      NaN
1      hot   summer  holiday
2   street     food      NaN
3  workout      NaN      NaN

In [7]:
df['missing'] = df.isnull().sum(axis=1)
print(df)

  hashtag1 hashtag2 hashtag3  missing
0     good    vibes      NaN        1
1      hot   summer  holiday        0
2   street     food      NaN        1
3  workout      NaN      NaN        2

### Exercise 16:

###### The `df` DataFrame is given below:

|    | investments |
|---:|:-------------|
| 0 | 100_000_000 |
| 1 | 100_000 |
| 2 | 30_000_000 |
| 3 | 100_500_000 |

###### Convert the `investments` column to `int` type and print the result to the console.

In [1]:
import pandas as pd

data_dict = {
    'investments': [
        '100_000_000', 
        '100_000', 
        '30_000_000', 
        '100_500_000'
    ]
}
df = pd.DataFrame(data=data_dict)

In [2]:
df

   investments
0  100_000_000
1      100_000
2   30_000_000
3  100_500_000

In [3]:
df['investments'] = df['investments'].replace('_','').astype(int)
print(df)

   investments
0    100000000
1       100000
2     30000000
3    100500000

### Exercise 17:

###### Load the IRIS dataset into the `data` variable using the `scikit-learn` package and the `load_iris()` function.

###### Then print all the keys of the `data` variable.

###### Tip:

###### More about the `load_iris()` function:

```python
https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_iris.html
```

In [4]:
from sklearn.datasets import load_iris

data = load_iris()
print(data.keys())

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

### Exercise 18:

###### The IRIS dataset was loaded into the `data` variable.

###### Print all feature variable names and all class names from the IRIS dataset as shown below.

In [5]:
import pandas as pd
from sklearn.datasets import load_iris

data = load_iris()

In [6]:
type(data)

sklearn.utils._bunch.Bunch

In [7]:
print(data['target_names'])
print(data.feature_names)

['setosa' 'versicolor' 'virginica']
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

### Exercise 18:

###### The IRIS dataset was loaded into the `data` variable.

###### Print all feature variable names and all class names from the IRIS dataset as shown below.

In [1]:
import pandas as pd
from sklearn.datasets import load_iris

data = load_iris()

In [2]:
type(data)

sklearn.utils._bunch.Bunch

In [3]:
print(data['target_names'])
print(data.feature_names)

['setosa' 'versicolor' 'virginica']
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']